Repository hmcts/probate-orchestrator-service, pull requests merged in 2019-10, with the labels that each got.

#133 App insights Correction
  Dockerfile
  Jenkinsfile_CNP
  charts/probate-orchestrator-service/Chart.yaml
  src/main/java/uk/gov/hmcts/insights/AppInsights.java
  src/main/resources/application.yml
  src/main/resources/bootstrap.yaml
Labels: ns:probate-orchestrator-service-pr-133

#134 Testing App insights
  Dockerfile
  Jenkinsfile_CNP
Labels: ns:probate-orchestrator-service-pr-134

#135 testing s2s key
  Dockerfile
  Jenkinsfile_CNP
  src/main/java/uk/gov/hmcts/probate/security/ServiceAuthConfiguration.java
Labels: ns:probate-orchestrator-service-pr-135

#138 Corrected s2s issue
  Jenkinsfile_CNP
  src/main/resources/application.yml
  src/main/resources/bootstrap.yaml
Labels: ns:probate-orchestrator-service-pr-138

#139 Added new version
  charts/probate-orchestrator-service/Chart.yaml
Labels: ns:probate-orchestrator-service-pr-139

#140 Add properties jar. Clean up
  build.gradle
  src/main/resources/bootstrap.yaml
Labels: ns:probate-orchestrator-service-pr-140

#143 Update appinsights env var
  src/main/resources/bootstrap.yaml
Labels: ns:probate-orchestrator-service-pr-143

#148 ASE To AKS Migration
  Jenkinsfile_CNP
Labels: ns:probate-orchestrator-service-pr-148

#152 Add dependabot config
  .dependabot/config.yml
Labels: ns:probate-orchestrator-service-pr-152
