Repository hmcts/probate-orchestrator-service, pull requests merged in 2021-03, with the labels that each got.

#450 DTSPB-1380 initiateExelaExtractDateRange method added to DataExtractServiceImpl.
  src/main/java/uk/gov/hmcts/probate/client/backoffice/BackOfficeApi.java
  src/main/java/uk/gov/hmcts/probate/controller/DataExtractController.java
  src/main/java/uk/gov/hmcts/probate/core/service/BackOfficeServiceImpl.java
  src/main/java/uk/gov/hmcts/probate/core/service/DataExtractServiceImpl.java
  src/main/java/uk/gov/hmcts/probate/service/BackOfficeService.java
  src/main/java/uk/gov/hmcts/probate/service/DataExtractService.java
  src/test/java/uk/gov/hmcts/probate/controller/DataExtractControllerTest.java
  src/test/java/uk/gov/hmcts/probate/core/service/BackOfficeServiceImplTest.java
  src/test/java/uk/gov/hmcts/probate/core/service/DataExtractServiceImplTest.java
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-450

#486 DTSPB-1659: set waiting docs to only run on 1st Jan
  dependency-check-suppressions.xml
  src/main/resources/application.yml
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-486

#485 DTSPB-1647 resolve bouncycastle suppression
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-485

#491 DTSPB-1650+52 resolve suppressions for beanutils and httpclient
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-491

#492 DTSPB-1649 tomcat related suppressions resolution
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-492

#493 DTSPB-1686 Resolve CVE-2021-22112 suppression
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-493

#497 DTSPB-1651 Resolve CVE-2020-15250 Junit
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-497

#498 DTSPB-1716 Resolve CWE79 suppression
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-498
