Repository hmcts/probate-orchestrator-service, pull requests merged in 2021-08, with the labels that each got.

#597 DTSPB-2177: fix
  audit.json
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-597

#600 DTSPB-2209 Integrate Fortify with Jenkins
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-600

#605 suppress CVE until spring boot upgrade
  dependency-check-suppressions.xml
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-605

#606 suppress CVE until spring boot upgrade
  dependency-check-suppressions.xml
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-606

#602 DTSPB-2276 - Bump chart.yaml java version to 3.6.0
  charts/probate-orchestrator-service/Chart.yaml
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-602

#608 Fix post tc issue
  build.gradle
  charts/probate-orchestrator-service/Chart.yaml
  charts/probate-orchestrator-service/values.yaml
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-608
