Repository hmcts/probate-orchestrator-service, pull requests merged in 2021-06, with the labels that each got.

#554 DTSPB-2020 Sync master code to all env when with every merge
  Jenkinsfile_CNP
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-554

#557 DTSPB-2095 Fix CVE-2021-22118
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-557

#567 DTSPB-2087 Add logs for getInviteData
  src/main/java/uk/gov/hmcts/probate/core/service/BusinessServiceImpl.java
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-567

#568 DTSPB-2153: enable SF daily extract
  src/main/resources/application.yml
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-568
