Repository hmcts/probate-orchestrator-service, pull requests merged in 2021-12, with the labels that each got.

#633 DTSPB-2493: Make ihtFormCompletedOnline optional
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-633

#634 DTSPB-2516 specify log4j version in dependencies
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-634

#635 DTSPB-2523 Update log4j version for dependencies to 2.16.0
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-635
