Repository hmcts/probate-orchestrator-service, pull requests merged in 2021-07, with the labels that each got.

#573 DTSPB-2087 log added.
  src/main/java/uk/gov/hmcts/probate/core/service/BusinessServiceImpl.java
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-573

#574 DTSPB-2175 update Dependencies
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-574

#580 DTSPB-2175 Dependabot open PRs fix
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-580

#586 DTSPB-2221 Upgrade tomcat version to fix dep failure
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-586

#592 DTSPB-2177 add nightly config
  Jenkinsfile_nightly
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-592

#595 DTSPB-2177: add security script for nightly tests
  security.sh
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-595

#596 DTSPB-2177: fix swagger
  build.gradle
  functional-output/.gitkeep
  security.sh
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-596
