Repository hmcts/probate-orchestrator-service, pull requests merged in 2022-03, with the labels that each got.

#645 DTSPB-2556: Break property name for test
  README.md
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-645

#650 DTSPB-2642 Java chart version upgrade
  charts/probate-orchestrator-service/Chart.yaml
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-650

#649 DTSPB-2616 Serenity report generation fix
  Jenkinsfile_CNP
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-649

#641 DTSPB-699: Investigate implementing Open ID Connect (OICD) - Reducing…
  build.gradle
  charts/probate-orchestrator-service/Chart.yaml
  charts/probate-orchestrator-service/values.yaml
  src/main/java/uk/gov/hmcts/probate/OrchestratorApplication.java
  src/main/java/uk/gov/hmcts/probate/core/service/SecurityUtils.java
  src/main/resources/application.yml
  src/test/java/uk/gov/hmcts/probate/core/service/SecurityUtilsTest.java
  src/test/resources/caveatForm.json
  src/test/resources/intestacyFormTest.json
  src/test/resources/paForm.json
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-641

#656 DTSPB-2671: suppress data bind issue
  dependency-check-suppressions.xml
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-656

#657 DTSPB-2671: remove suppression
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-657

#659 Revert "Dtspb 699 open"
  build.gradle
  charts/probate-orchestrator-service/Chart.yaml
  src/main/java/uk/gov/hmcts/probate/OrchestratorApplication.java
  src/main/java/uk/gov/hmcts/probate/core/service/SecurityUtils.java
  src/main/resources/application.yml
  src/test/java/uk/gov/hmcts/probate/core/service/SecurityUtilsTest.java
  src/test/resources/caveatForm.json
  src/test/resources/intestacyFormTest.json
  src/test/resources/paForm.json
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-659

#662 Dtspb 2613 upgrade spring boot
  build.gradle
  dependency-check-suppressions.xml
  src/functionalTest/java/uk/gov/hmcts/probate/functional/TestContextConfiguration.java
  src/main/java/uk/gov/hmcts/probate/configuration/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/probate/security/SecurityConfiguration.java
  src/main/resources/application.yml
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-662

#661 DTSPB-1493 add checklist items to tets payload
  build.gradle
  src/functionalTest/resources/json/validBulkScanCoversheet.json
  src/test/resources/businessDocuments/validBulkScanCoverSheet.json
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-661
