Repository hmcts/probate-orchestrator-service, pull requests merged in 2022-04, with the labels that each got.

#664 DTSPB-2704: Upgrade Springboot version 2.6.6 for probate services
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-664

#668 DTSPB-2747 Fix CVE-2022-22968
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-668

#667 Dtspb 2544 pp notorial access
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-667
