Repository hmcts/probate-orchestrator-service, pull requests merged in 2022-10, with the labels that each got.

#707 DTSPB-3033 Supress CVE-2022-38752
  dependency-check-suppressions.xml
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-707

#712 DTSPB-3039 Suppress CVE-2022-42003,CVE-2022-42004
  dependency-check-suppressions.xml
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-712

#711 DTSPB-2997 hand off flag
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-711

#708 DTSPB-2407-PA8A-and-DTSPB-2656-PA8B: point to preview
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-708
