Repository hmcts/probate-orchestrator-service, pull requests merged in 2023-12, with the labels that each got.

#799 DTSPB-3906 suppress CVE-2023-33202
  dependency-check-suppressions.xml
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-799

#806 update suppressions
  dependency-check-suppressions.xml
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-806

#798 DTSPB-3899 remove fortify
  Jenkinsfile_nightly
Labels: ns:probate, prd:probate, nightly, rel:probate-orchestrator-service-pr-798

#809 update cves
  dependency-check-suppressions.xml
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-809
