Repository hmcts/probate-orchestrator-service, pull requests merged in 2025-08, with the labels that each got.

#1318 bump commonmark version
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-1318

#1334 DTSPB-4896 Change getCase to getCaseId
  src/main/java/uk/gov/hmcts/probate/core/service/BusinessServiceImpl.java
  src/main/java/uk/gov/hmcts/probate/core/service/SubmitServiceImpl.java
  src/test/java/uk/gov/hmcts/probate/core/service/BusinessServiceImplTest.java
  src/test/java/uk/gov/hmcts/probate/core/service/SubmitServiceImplTest.java
Labels: ns:probate, prd:probate, enable_keep_helm, rel:probate-orchestrator-service-pr-1334

#1343 DTSPB-4368: Add swagger annotations
  build.gradle
Labels: ns:probate, prd:probate, nightly, rel:probate-orchestrator-service-pr-1343

#1365 DTSPB-4661 bump commons
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-orchestrator-service-pr-1365

#1346 DTSPB-4740 Point PR
  build.gradle
Labels: ns:probate, prd:probate, enable_keep_helm, aat/no-changes, prod/no-changes, rel:probate-orchestrator-service-pr-1346
